# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

autoload -U colors && colors

# The following lines were added by compinstall
zstyle ':completion:*' completer _complete _ignored _approximate

unsetopt menu_complete   # do not autoselect the first completion entry
unsetopt flowcontrol
setopt auto_menu         # show completion menu on successive tab press
setopt complete_in_word
setopt always_to_end

zstyle ':completion:*' insert-unambiguous true
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' matcher-list '' 'm:{[:lower:]}={[:upper:]}' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}'
zstyle ':completion:*' original true
zstyle ':completion:*' menu select
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' verbose true
zstyle :compinstall filename '/home/maxwai/.zshrc'

autoload -Uz compinit
compinit -C
_comp_options+=(globdots)
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=100000
SAVEHIST=100000
setopt EXTENDED_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_FIND_NO_DUPS
setopt HIST_SAVE_NO_DUPS
setopt HIST_BEEP

setopt autocd autopushd
# End of lines configured by zsh-newuser-install
alias rm='rm -I' # Ask before removal
alias cp='cp -i' # Ask before copy
alias mv='mv -i' # Ask before move
alias android='scrcpy' # map scrpy (Android Mirror via USB) to android

# Key Bings
bindkey '^[[3~' delete-char # ENTF
bindkey '^[[F' end-of-line # ENDE
bindkey '^[[H' beginning-of-line # POS1
bindkey '^[[1;5C' forward-word # STRG + RIGHT ARROW
bindkey '^[[1;5D' backward-word # STRG + LEFT ARROW
bindkey '^H' backward-kill-word # STRG + BACKSPACE

# PROMPT
#NAME="%B%{$fg[green]%}%n%b"
#DIR="%B%{$fg[blue]%}%5~%b"
#SEP_COLOR="%{$reset_color%}"
#export PROMPT="${NAME}${SEP_COLOR}:${DIR}${SEP_COLOR}$ "

export ZSH="/home/maxwai/.oh-my-zsh"
ZSH_THEME="powerlevel10k/powerlevel10k"

plugins=(git
	 copypath
	 copyfile
	 dnf
	 sudo
	 docker
	 docker-compose
	 stack)

export ZSH_DISABLE_COMPFIX=true
source $ZSH/oh-my-zsh.sh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

DISABLE_UPDATE_PROMPT=true

#path+=('/home/maxwai/.cargo/bin')
export PATH

# dotdrop alias
alias dotdrop='/home/maxwai/dotfiles/dotdrop.sh --cfg=/home/maxwai/dotfiles/config.yaml'

# git alias
alias git_lrz='git config user.email m.waidelich@hm.edu; git config user.signingkey EB95B6B107D905C3'
alias git_teiimo='git config user.email max.waidelich@teiimo.com; git config user.signingkey 956E750029EDAC1F'
alias git_private='git config user.email maximilian.waidelich@gmail.com; git config user.signingkey 3F697FD9B5B4C657'

export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/usr/local/lib"

# matlab alias
alias activate_matlab='/usr/local/MATLAB/R2021b/bin/activate_matlab.sh'

# gedit replacement
alias gedit="gnome-text-editor"


#tmp alias
alias dnf_fix_smb='sudo dnf downgrade libsmbclient'

[ -f "/home/maxwai/.ghcup/env" ] && source "/home/maxwai/.ghcup/env" # ghcup-env
