config:
  backup: true
  create: true
  dotpath: dotfiles
  check_version: true
dotfiles:
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_p10k.zsh:
    src: p10k.zsh
    dst: ~/.p10k.zsh
  f_taskrc:
    src: taskrc
    dst: ~/.taskrc
  f_btop.conf:
    src: config/btop/btop.conf
    dst: ~/.config/btop/btop.conf
profiles:
  maxi-fedora:
    dotfiles:
    - f_bashrc
    - f_zshrc
    - f_p10k.zsh
    - f_taskrc
    - f_btop.conf
  maxi-framework:
    dotfiles:
    - f_bashrc
    - f_zshrc
    - f_p10k.zsh
    - f_taskrc
    - f_btop.conf
  maxi-server:
    dotfiles:
    - f_bashrc
    - f_zshrc
    - f_p10k.zsh
    - f_btop.conf

